src/App.tsx
src/theme/theme.ts

feat: add a custom theme to the application

---

src/components/Menu/MenuSmall.tsx
src/components/Menu/NavbarMenu.tsx

Navbar Menu is a dropdown menu within the navbar and small Menu is three dots that dropdowns menu. The small menu is for the display on smaller screens. Closes #40

Feat: Added Menu component with two variants: Navbar Menu and Small Menu

---

src/components/Footer.tsx

feat: add Footer component

---

src/components/Search.tsx

feat: add Search component

---

src/components/Icon.tsx

feat: add Icon component

---

src/components/Users.tsx

feat: add Users component

---

package-lock.json
package.json
src/App.tsx
src/index.tsx
src/pages/landing.tsx
src/pages/newCriteria.tsx

This is the new criteria page. It resolves #22 . There is also some links I added in the app page to help navigate easily to this page.

Feat: Added the new criteria page

---

src/App.tsx
src/index.tsx
src/pages/otherNewOption.tsx

feat(pages): create other options page

---

README.md

This closes #99, #101 , #102 , #103 , #104 , #105

docs: update README.md on the description of Decision Maker, the authors and the high fidelity prototype

---

src/components/Button.tsx
src/pages/NewCriteria.tsx
src/pages/OtherNewCriteria.tsx

Changes on NewCriteria Page
- Added a form to take in the text submitted and a handle submit function
- The handle submit function navigates to OtherNewCriteria page after the data is successfully entered in the form using 'useNavigate'
- Used 'Button' component instead of 'Custom Button' to enable adding onSubmit and styled it like the Custom Button component -The handle submit function displays the form data on the console
Changes on Another New Criteria
- Made the page responsive by re-setting the grid : for search bar and the display of the criteria
- Edited the 'Edit Criteria' to a 'Delete' Button
- Added a form on the search bar to take in text for searching and filtering the criteria
- Added a handleSubmit function to the form to display the data entered in the text field to the …

Feat: Added edits on the New Criteria Page and Another New Criteria Page

---

src/App.css
src/App.tsx
src/components/BackButton.tsx
src/components/Breadcrumbs.tsx
src/components/Header.tsx
src/components/HeroSection.tsx
src/components/Layout.tsx
src/contexts/BreadcrumbsProvider.tsx
src/pages/AboutUs.tsx
src/pages/ContactUs.tsx
src/pages/DecisionModel.tsx
src/pages/EvaluateCriteriaPage.tsx
src/pages/EvaluateOptionsPage.tsx
src/pages/Home.tsx
src/pages/NewCriteria.tsx
src/pages/NewDecision.tsx
src/pages/NewOption.tsx
src/pages/OtherNewCriteria.tsx
src/pages/OtherNewOption.tsx
src/pages/PreviousDecision.tsx
src/pages/ResultsPage.tsx

added a back button to every pages
add breadcrumbs dynamically to application
Remove search bar component from navigation
enhances css styling across pages for uniformity
removed unused imports
closes #80

feat: Adjust Routes to pages

---

src/pages/Login.tsx
src/pages/Register.tsx

Added Back buttons to navigate back to home from login and register pages.

update: Added back buttons to navigate back to home from the pages

---

src/pages/Register.tsx

Made a small change on the registration page

update: Update on the register page

---

src/components/Header.tsx
src/components/PairwiseComparison.tsx
src/pages/EvaluateCriteriaPage.tsx
src/pages/EvaluateOptionsPage.tsx
src/pages/Home.tsx
src/pages/Login.tsx
src/pages/NewDecision.tsx
src/pages/PreviousDecision.tsx
src/pages/Register.tsx
src/pages/ResultsPage.tsx

modified:   src/components/Header.tsx
modified:   src/components/PairwiseComparison.tsx
modified:   src/pages/EvaluateCriteriaPage.tsx
modified:   src/pages/EvaluateOptionsPage.tsx
modified:   src/pages/Home.tsx
modified:   src/pages/Login.tsx
modified:   src/pages/NewDecision.tsx
modified:   src/pages/PreviousDecision.tsx
modified:   src/pages/Register.tsx
modified:   src/pages/ResultsPage.tsx

feat: adjusted responsiveness of the pages below

---

src/components/Button.tsx
src/components/Header.tsx
src/components/interfaces/ButtonInterface.ts
src/pages/EvaluateCriteriaPage.tsx
src/pages/EvaluateOptionsPage.tsx
src/pages/ExistingCriteria.tsx
src/pages/Login.tsx
src/pages/PreviousDecision.tsx
src/pages/Register.tsx
src/pages/ResultsPage.tsx

add previous decisons to read from database

feat: add conclusion modal to result page

---

src/pages/PreviousDecision.tsx

future work: diplay decision name

fix: previous decision page

---

src/pages/ExistingCriteria.tsx

- Replaced hardcoded criteria categories with dynamic fetching from the database.
- Fixed criteria data handling by removing incorrect `.split()` method.
- Improved page layout to reduce excessive scrolling and make the submit button more accessible.
- Added search functionality to filter criteria categories more effectively.

feat: store criteria categories in DB and enhance layout

---

src/components/HeroSection.tsx
src/pages/ExistingCriteria.tsx
src/pages/NewCriteria.tsx
src/pages/PreviousDecision.tsx

also worked on previous decisions page to display decision name alao changed bg color of herosection

feat: new custom critera saved to db and displayed on page

---

src/pages/EvaluateCriteriaPage.tsx
src/pages/ExistingCriteria.tsx
src/pages/NewCriteria.tsx

fixed error with closure of add criteria function

154 assigning wages

---

src/pages/ExistingCriteria.tsx

- Adjusted StyledChip component to ensure better contrast for selected criteria on hover.
- Updated ListItem styles to maintain good visibility and contrast when a selected criterion is hovered over.

fix(ui): improve visibility of selected criteria on hover

---

src/pages/PreviousDecision.tsx

- Updated the handleSeeCriteria function to use the already fetched decisions from the database rather than refetching from the database
- Populated the barcharts showing comparisons between options for each criterion
- Created a barchart to show the preferred option as well as the order of preference for the decision

feat: update previous decision page to contain comparisons between options for each criterion

---

src/components/contact-input.tsx
src/pages/ContactUs.tsx

Fixed the Contact Us to enable us to view the messages from the page via email

Fix: Update on the viewing of contents of the Contact Us

---

src/pages/ContactUs.tsx

- Added a feedback form link to the Contact Us page.
- Styled the link to be more prominent and engaging for users.

feat(ContactUs): add feedback form link
